In [5]:
import numpy as np

# Array

Conjunto de dados -
Dimensões diferentes

ndarrays - arrays com n dimensões

Vetor - Uma dimensão

Matriz - Duas dimensões

Tensor - Três ou mais dimensões



In [6]:
a = np.array([1,2,3,4,5,6])


In [7]:
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
zero = np.zeros(shape = (5,3,6))
print (zero)
#zeros. Cria array só com zeros.
#5 dimensões (vertical), 3 linhas (horizontal), 6 colunas(tamanho de dimensõse)
#Está em 3D. Porém estamos vendo isso em 2D

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [9]:
um = np.ones(shape = (2,3))
print(um)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
vazio = np.empty(1)
print(vazio)

[1.]


In [11]:
arr = np.arange(10)
print(arr)
arr2 = np.arange(1, 11,1)
#começo, fim, incremento
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
#sequencias. Sequencia linear
#começo, fim, num= 50, endpoint,
#endpoint é o numero no final, decimaol para arredondato
#num é quantos elementos ele vai mostrar
#retstep pode ser true ou false. Diferença de quanto em quanto ele está fazendo. Reta em termo de valores
seq = np.linspace(0, 100, num= 20, endpoint = False)
print(seq)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]


Descobrindo tamanho

In [13]:
print(zero.shape)
#5 em uma dimensão, 3 em outra, 6 em outra
print(zero.size)
#90 dados
print(zero.ndim)
#numero de dimensões. 3. Uma dimensão 3, outra 5, 6. Assim, 3 dimensões

(5, 3, 6)
90
3


Mudando tamanho. Agregar outra dimensão



In [14]:
um1 = um.reshape([6,1])
print(um1)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [15]:
#horizontal, vertical, tamanho
#newaxis cria apenas uma nova dimensão

a = np.array([1,2,3])
print(a.shape)
print(a.ndim)
print(a)
print()
#Uma dimensão de tamanho 3

a2 = a[np.newaxis, :]
print(a2.shape)
print(a2.ndim)
print(a2)
print()
#Duas dimensões. Uma de tamanho 1 e a outra de tamanho 3

a21 = a[:, np.newaxis]
print(a21.shape)
print(a21.ndim)
print(a21)
print()
#Duas dimensões. Uma de tamanho 1 e a outra de tamanho 3

# : é pegar todos os dados que tinha dentro de a, e c

(3,)
1
[1 2 3]

(1, 3)
2
[[1 2 3]]

(3, 1)
2
[[1]
 [2]
 [3]]



Sort

In [16]:
opa = np.sort(seq)
print(opa)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]


In [24]:
print(a21[0]) #quer o item 0, primeira item, desta dimensão
print(a21[0][0]) #quer o item 0 da primeira dimensão


[1]
1



Concatenando arrays

In [26]:
#juntar arrays diferentes
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
d = np.concatenate((b,a))
print(c)
print(d)


[1 2 3 4 5 6]
[4 5 6 1 2 3]


Consultar itens de uma array



In [33]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a.shape)
print("--------------")
maior_8 = a[a<8]
print(maior_8)
resto = a[a%2==0]
print(resto)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
--------------
[1 2 3 4 5 6 7]
[ 2  4  6  8 10 12]


Operações



In [34]:
a = np.array([1,2,3])
#calculos
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())

6
3
1
2.0


In [35]:
from numpy.random import default_rng

In [37]:
rng = default_rng()
aleatorio = rng.integers(10, size=(2,4))
#aleatorio é trazer numero aleatorio no máximo até 10, de 2 dimensões, onde uma tenha tamanho 2 e outra 4
print(aleatorio)

[[7 9 0 2]
 [6 6 6 3]]


Arrays é para quantidade de dados grande. Melhor que lista nestes casos.

In [40]:
a = np.array([1,2,3,4,5,6,7,8]) 
#arrays só permite que todos os dados sejam de um tipo. Se um for string, todos serão strings. 
#Não permite tipos de dados diferentes
print(a)
print(type(a))
print('----------')
lista_a= [1,2,3,4,5,6,7,8]
print(lista_a)
print(type(lista_a))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
----------
[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>


# Revisão Numpy para Plotly

In [46]:
matriz1 = np.array([[1,3,4],[4,5,6],[1,2,3]])

matriz2 = np.array(
    [[2,1,0],
    [5,7,11],
    [12,13,0]])

print (matriz1)
print(matriz2)

[[1 3 4]
 [4 5 6]
 [1 2 3]]
[[ 2  1  0]
 [ 5  7 11]
 [12 13  0]]


In [47]:
print(matriz1 + matriz2) 
#soma de matrizes

[[ 3  4  4]
 [ 9 12 17]
 [13 15  3]]


In [49]:
numero = 5
print(matriz1*numero)

[[ 5 15 20]
 [20 25 30]
 [ 5 10 15]]


In [52]:
np.dot(matriz1,matriz2)


array([[ 65,  74,  33],
       [105, 117,  55],
       [ 48,  54,  22]])

In [54]:
np.random.randint(10)
#menor, maior, quantidade de elementos


7